version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - slack/status:
          fail_only: true

  test:
    parallelism: 4
    docker:
      - image: cimg/ruby:2.7-browsers
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: gt_pupilfirst_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: test
      JAVASCRIPT_DRIVER: headless_chrome
      SPEC_USER_TIME_ZONE: Etc/UTC
      SPEC_RETRY_COUNT: 2
      ALLOW_EMAIL_SIGN_IN: true
      CAPYBARA_MAX_WAIT_TIME: 7
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load
          environment:
            DATABASE_URL: "postgres://postgres:password@localhost:5432/gt_pupilfirst_test"
      - run:
          name: Test
          command: |
            mkdir -p /tmp/test-results/rspec
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bin/rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
          environment:
            DATABASE_URL: "postgres://postgres:password@localhost:5432/gt_pupilfirst_test"
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: ./tmp/capybara
      - slack/status:
          fail_only: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
