name: CI

on:
  workflow_dispatch:
  push:
    branches: ['*']
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
      JAVASCRIPT_DRIVER: headless_chrome
      DB_HOST: localhost
      DB_NAME_TEST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CAPYBARA_MAX_WAIT_TIME: 5
      SPEC_USER_TIME_ZONE: Etc/UTC
      SPEC_RETRY_COUNT: 2
      ALLOW_EMAIL_SIGN_IN: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          bundle exec rake db:schema:load
      - name: Precompile Assets
        run: |
          bundle exec rails assets:precompile
          echo Precompilation complete. Cleaning assets...
          bundle exec rails assets:clean
          echo Cleaning complete! All done.
      - name: Specs
        run: bundle exec rspec ./spec/requests/api/schools/course_requests_spec.rb:36
